### PR TITLE
Tweak `Error` representation

### LINKED ISSUE #568: `Error` on targets where `RawOsError` is not equal to `i32`
Previously, all Rust targets with `std` were using `i32` for "raw" OS error codes, i.e. `io::Error::raw_os_error/from_raw_os_error` have accepted `i32`. We have encoded this assumption in `Error::raw_os_error`, `fmt::Debug/Display`, and `From<Error> for io::Error` implementations.

But in the recently added UEFI `std` implementation `usize` is used for error codes instead as per [UEFI spec](https://uefi.org/specs/UEFI/2.10/Apx_D_Status_Codes.html). It's reflected by the new (Nightly-only) type alias [`RawOsError`](https://doc.rust-lang.org/std/io/type.RawOsError.html)

For now, we just added `cfg`-based exceptions for UEFI targets in the relevant internal implementations (see #566). But it may be worth to reconsider our use of `NonZeroU32` for `Error` internal representation and return type of `Error::raw_os_error`.

cc @usamoi

### PR DESCRIPTION
**Pull request by newpavlov**
On UEFI targets `Error` is now represented as `NonZeroUsize` and on other targets as `NonZeroI32`. In the former case OS errors have the highest bit set to 1, while in the latter case OS errors are represented as negative integers.

Additionally, this PR removes `Error::INTERNAL_START` and `Error::CUSTOM_START` associated constants since the constants are no longer relevant and the inner representation is an internal detail. This is technically a breaking change, but I highly doubt that downstream users rely on them since they can not be used for anything useful, so we can consider it as a "fix" of unintentionally exported constants.

Closes #568

### CODE REVIEW

File: src/error.rs [hunk 1]
```diff
@@ -79,27 +89,38 @@ impl Error {
...
+            }
+        }
+
+        #[cfg(not(target_os = "uefi"))]
+        {
+            if code >= 0 {
+                return None;
+            }
+            #[cfg(not(target_os = "solid_asp3"))]
+            let code = code.checked_neg()?;
```
Comment (newpavlov) [inline src/error.rs:107]: I am not sure whether we should do this negation on WASIp1 and Hermit.

**Comment by newpavlov** [comment]
@josephlr 
Note that I plan to release v0.3.2. after merging this (with a separate release PR), so if you have any objections or suggestions about the recently merged PR it's worth to sort them out before that.

**Comment by josephlr** [comment]
> @josephlr Note that I plan to release v0.3.2. after merging this (with a separate release PR), so if you have any objections or suggestions about the recently merged PR it's worth to sort them out before that.

That sounds like a good plan, I'm currently working through some of the recently merged PRs. I should hopefully be done by tomorrow. Thanks for all the fixes and reviews. Sorry I haven't had a huge amount of time for this recently.

File: src/error.rs [hunk 2]
```diff
@@ -38,28 +45,33 @@ impl Error {
...
-    /// `1..Error::INTERNAL_START`. Thus, for the result `r`,
-    /// `r == Self::UNEXPECTED || r.raw_os_error().unsigned_abs() == code`.
+    /// replaced with `Error::UNEXPECTED` in unexpected cases.
     ///
     /// [1]: https://doc.rust-lang.org/std/io/struct.Error.html#method.from_raw_os_error
     #[allow(dead_code)]
-    pub(super) fn from_os_error(code: u32) -> Self {
-        match NonZeroU32::new(code) {
-            Some(code) if code.get() < Self::INTERNAL_START => Self(code),
+    pub(super) fn from_os_error(code: RawOsError) -> Self {
```
Comment (josephlr) [inline src/error.rs:69]: If we want to handle all the error negating/checking in here, this could be:

On UEFI:
```rust
if code & UEFI_ERROR_FLAG  == 0 {
  Self::UNEXPECTED
} else {
  Self(NonZeroRawOsError::new(code).unwrap())
}
```

On platforms where `RawOsError` is expected to be positive:
```rust
match code.checked_neg() {
  None => Self::ERRNO_NOT_POSITIVE,
  Some(e) if e >= 0 => Self::ERRNO_NOT_POSITIVE,
  Some(e) => Self(NonZeroRawOsError::new(e).unwrap())
}
```
and on platforms where `RawOsError` is expected to be negative:
```rust
if code >= 0 {
  Self::UNEXPECTED
} else {
  Self(NonZeroRawOsError::new(code).unwrap())
}
```
then we just undo things in `raw_os_error`

File: src/error.rs (hunk 1 above)
Comment (josephlr) [reply src/error.rs:109]: I think we should figure out where they define their error constants, and use whatever convention is in place there.

**Review by josephlr — COMMENTED** [review]
I like this change, i have some suggestions on how we might make this easier to follow

**Comment by josephlr** [comment]
> > @josephlr Note that I plan to release v0.3.2. after merging this (with a separate release PR), so if you have any objections or suggestions about the recently merged PR it's worth to sort them out before that.
> 
> That sounds like a good plan, I'm currently working through some of the recently merged PRs. I should hopefully be done by tomorrow. Thanks for all the fixes and reviews. Sorry I haven't had a huge amount of time for this recently.

I didn't quite get to all of the PRs today, but a quick skim shows nothing glaringly bad. I have a few ideas for PRs that might clean things up, but nothing that should block release.

File: src/error.rs [hunk 3]
```diff
@@ -38,28 +45,33 @@ impl Error {
...
-    /// Codes at or above this point can be used by users to define their own
-    /// custom errors.
+    #[deprecated]
+    #[doc(hidden)]
     pub const CUSTOM_START: u32 = (1 << 31) + (1 << 30);
 
+    /// Internal errors can be in the range of 2^16..2^17
+    const INTERNAL_START2: RawOsError = 1 << 16;
+    /// Custom errors can be in the range of 2^17..(2^17 + 2^16)
+    const CUSTOM_START2: RawOsError = 1 << 17;
```
[the remark this answers is not in the document]
Comment (newpavlov) [reply src/error.rs:59]: It's not only about the value change, but also about the constants type (i.e. instead of `u32` it's now `i32` or `usize`).

File: src/error.rs (hunk 1 above)
Comment (newpavlov) [reply src/error.rs:109]: We probably should look into what is done by `std`. After all, the primary use case for the error codes is to get error strings which are included with `std`/`libc`.

File: src/util_libc.rs [hunk 4]
```diff
@@ -34,14 +34,16 @@ cfg_if! {
...
 
-    // c_int-to-u32 conversion is lossless for nonnegative values if they are the same size.
-    const _: () = assert!(core::mem::size_of::<libc::c_int>() == core::mem::size_of::<u32>());
-
-    match u32::try_from(errno) {
-        Ok(code) if code != 0 => Error::from_os_error(code),
-        _ => Error::ERRNO_NOT_POSITIVE,
+    if errno > 0 {
+        let code = errno
+            .checked_neg()
```
[the remark this answers is not in the document]
Comment (newpavlov) [reply src/util_libc.rs:42]: The problem is that different targets have different conventions around error codes. We could use different `Error` representations for targets which use negative and positive error codes, but it would be... extremely annoying. Assuming that we use the same representation for both cases, we now need to decide whether we want to store OS errors as negative or positive codes.

I think that the negative approach is better since we can always negate positive codes, while with negative codes possibility of `i32::MIN` causes issues. Yes, it means that in `raw_os_error` we have to "un-negate" the code while accounting for `i32::MIN`, but since it's a relatively rarely used method, I think it's better than to introduce additional checking branches to backends.

Arguably, `libc` with its `errno` is the weird one (personally, I hate it with passion). Linux kernel and most other targets use the negative error code convention for obvious reasons.

File: src/error.rs (hunk 2 above)
Comment (newpavlov) [reply src/error.rs:69]: Hm. The problem with this approach is that we would have to manually list all targets which use positive (or negative) codes in the `error` module and do it twice.

But we kind of already do it with `#[cfg(not(target_os = "solid_asp3"))]`...

Comment (newpavlov) [reply src/error.rs:82]: I tweaked the code a bit. I left the `ERRNO_NOT_POSITIVE` check in the `last_os_error` function, but otherwise it's close to your proposal.

File: src/error.rs (hunk 1 above)
Comment (newpavlov) [reply src/error.rs]: I added the comment for all targets which rely on `from_os_error`: https://github.com/rust-random/getrandom/blob/error_tweak/src/error.rs#L106-L114

File: src/error.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (newpavlov) [reply src/error.rs]: I marked the old constants private and removed `INTERNAL/CUSTOM_START2`.

File: src/error.rs [hunk 5]
```diff
@@ -38,28 +43,25 @@ impl Error {
...
-    /// custom errors.
-    pub const CUSTOM_START: u32 = (1 << 31) + (1 << 30);
+    /// Internal errors can be in the range of 2^16..2^17
+    const INTERNAL_START: RawOsError = 1 << 16;
+    /// Custom errors can be in the range of 2^17..(2^17 + 2^16)
+    const CUSTOM_START: RawOsError = 1 << 17;
 
     /// Creates a new instance of an `Error` from a particular OS error code.
     ///
     /// This method is analogous to [`std::io::Error::from_raw_os_error()`][1],
```
Comment (josephlr) [inline src/error.rs:53]: This documentation now doesn't match the implementation, as we now:
  - On UEFI or `solid_asp3`: we take the raw error (which is already negative in error cases)
  - On all other platforms: we take the negative of the raw error

We should either:
  - Update the docs
  - have `Error::from_os_error` work like `Error::from_raw_os_error`

as this method isn't public, we could even change the name of `Error::from_os_error` to be something like `Error::from_neg_os_error`. I'm fine considering the UEFI error codes to be "negative" as they have the high-bit set.

**Review by josephlr — APPROVED** [review]
Looks good to me, do we want to make the changes to `efi_rng.rs` in this PR, or in a followup PR.

File: src/error.rs (hunk 5 above)
Comment (newpavlov) [reply src/error.rs]: I introduced a separate method gated on UEFI targets to make it a bit more clearer.

**Comment by newpavlov** [comment]
>do we want to make the changes to efi_rng.rs in this PR

I added commits which change `efi_rng` appropriately (I thought I already did it, but I guess It has slipped my mind for some reason).
